AllCops:
  Exclude:
    - vendor/**/*
    - lib/slack/web/api/slack-api-ref/**/*

Metrics:
  Enabled: false

Metrics/LineLength:
  Max: 512

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

inherit_from: .rubocop_todo.yml
