# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module AccountsChanged
#         # The list of accounts a user is signed into has changed.
#         # @see https://api.slack.com/events/accounts_changed
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/accounts_changed.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['accounts_changed'] = Slack::RealTime::EventHandlers::AccountsChanged
