# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module BotAdded
#         # An integration bot was added.
#         # @see https://api.slack.com/events/bot_added
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/bot_added.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['bot_added'] = Slack::RealTime::EventHandlers::BotAdded
