# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module ChannelDeleted
#         # A team channel was deleted.
#         # @see https://api.slack.com/events/channel_deleted
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/channel_deleted.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['channel_deleted'] = Slack::RealTime::EventHandlers::ChannelDeleted
