# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module DndUpdatedUser
#         # Do not Disturb settings changed for a team member.
#         # @see https://api.slack.com/events/dnd_updated_user
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/dnd_updated_user.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['dnd_updated_user'] = Slack::RealTime::EventHandlers::DndUpdatedUser
