# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module EmojiChanged
#         # A team custom emoji has been added or changed.
#         # @see https://api.slack.com/events/emoji_changed
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/emoji_changed.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['emoji_changed'] = Slack::RealTime::EventHandlers::EmojiChanged
