# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module FileCommentEdited
#         # A file comment was edited.
#         # @see https://api.slack.com/events/file_comment_edited
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/file_comment_edited.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['file_comment_edited'] = Slack::RealTime::EventHandlers::FileCommentEdited
