# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module FileUnshared
#         # A file was unshared.
#         # @see https://api.slack.com/events/file_unshared
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/file_unshared.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['file_unshared'] = Slack::RealTime::EventHandlers::FileUnshared
