# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module FileCreated
#         # A file was created.
#         # @see https://api.slack.com/events/file_created
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/file_created.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['file_created'] = Slack::RealTime::EventHandlers::FileCreated
