# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module GroupJoined
#         # You joined a private group.
#         # @see https://api.slack.com/events/group_joined
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/group_joined.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['group_joined'] = Slack::RealTime::EventHandlers::GroupJoined
