# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module GroupHistoryChanged
#         # Bulk updates were made to a group's history.
#         # @see https://api.slack.com/events/group_history_changed
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/group_history_changed.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['group_history_changed'] = Slack::RealTime::EventHandlers::GroupHistoryChanged
