# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module GroupLeft
#         # You left a private group.
#         # @see https://api.slack.com/events/group_left
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/group_left.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['group_left'] = Slack::RealTime::EventHandlers::GroupLeft
