# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module GroupMarked
#         # A private group read marker was updated.
#         # @see https://api.slack.com/events/group_marked
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/group_marked.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['group_marked'] = Slack::RealTime::EventHandlers::GroupMarked
