# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module GroupOpen
#         # You opened a group channel.
#         # @see https://api.slack.com/events/group_open
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/group_open.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['group_open'] = Slack::RealTime::EventHandlers::GroupOpen
