# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module ImCreated
#         # A direct message channel was created.
#         # @see https://api.slack.com/events/im_created
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/im_created.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['im_created'] = Slack::RealTime::EventHandlers::ImCreated
