# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module PinRemoved
#         # A pin was removed from a channel.
#         # @see https://api.slack.com/events/pin_removed
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/pin_removed.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['pin_removed'] = Slack::RealTime::EventHandlers::PinRemoved
