# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module ReactionAdded
#         # A team member has added an emoji reaction to an item.
#         # @see https://api.slack.com/events/reaction_added
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/reaction_added.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['reaction_added'] = Slack::RealTime::EventHandlers::ReactionAdded
