# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module ReactionRemoved
#         # A team member removed an emoji reaction.
#         # @see https://api.slack.com/events/reaction_removed
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/reaction_removed.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['reaction_removed'] = Slack::RealTime::EventHandlers::ReactionRemoved
