# This file was auto-generated by lib/tasks/real_time.rake

# module Slack
#   module RealTime
#     module EventHandlers
#       module TeamPlanChange
#         # The team billing plan has changed.
#         # @see https://api.slack.com/events/team_plan_change
#         # @see https://github.com/dblock/slack-api-ref/blob/master/events/team_plan_change.json
#         def self.call(_client, _data)
#           # TODO
#         end
#       end
#     end
#   end
# end
#
# Slack::RealTime::Client.events['team_plan_change'] = Slack::RealTime::EventHandlers::TeamPlanChange
