# This file was auto-generated by lib/tasks/web.rake

require_relative 'endpoints/pins'
require_relative 'endpoints/bots'
require_relative 'endpoints/oauth'
require_relative 'endpoints/mpim'
require_relative 'endpoints/chat'
require_relative 'endpoints/auth'
require_relative 'endpoints/dnd'
require_relative 'endpoints/reactions'
require_relative 'endpoints/emoji'
require_relative 'endpoints/stars'
require_relative 'endpoints/groups'
require_relative 'endpoints/usergroups_users'
require_relative 'endpoints/usergroups'
require_relative 'endpoints/search'
require_relative 'endpoints/dialog'
require_relative 'endpoints/team'
require_relative 'endpoints/team_profile'
require_relative 'endpoints/conversations'
require_relative 'endpoints/rtm'
require_relative 'endpoints/users'
require_relative 'endpoints/users_profile'
require_relative 'endpoints/files'
require_relative 'endpoints/files_comments'
require_relative 'endpoints/api'
require_relative 'endpoints/im'
require_relative 'endpoints/apps_permissions'
require_relative 'endpoints/migration'
require_relative 'endpoints/reminders'
require_relative 'endpoints/channels'

module Slack
  module Web
    module Api
      module Endpoints
        include Slack::Web::Api::Mixins::Channels
        include Slack::Web::Api::Mixins::Users
        include Slack::Web::Api::Mixins::Groups

        include Pins
        include Bots
        include Oauth
        include Mpim
        include Chat
        include Auth
        include Dnd
        include Reactions
        include Emoji
        include Stars
        include Groups
        include UsergroupsUsers
        include Usergroups
        include Search
        include Dialog
        include Team
        include TeamProfile
        include Conversations
        include Rtm
        include Users
        include UsersProfile
        include Files
        include FilesComments
        include Api
        include Im
        include AppsPermissions
        include Migration
        include Reminders
        include Channels
      end
    end
  end
end
