# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module BotChanged
          # An integration bot was changed.
          # @see https://api.slack.com/events/bot_changed
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/bot_changed.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['bot_changed'] = Slack::RealTime::Store::Handlers::BotChanged
