# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module ChannelMarked
          # Your channel read marker was updated.
          # @see https://api.slack.com/events/channel_marked
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/channel_marked.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['channel_marked'] = Slack::RealTime::Store::Handlers::ChannelMarked
