# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module ChannelUnarchive
          # A team channel was unarchived.
          # @see https://api.slack.com/events/channel_unarchive
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/channel_unarchive.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['channel_unarchive'] = Slack::RealTime::Store::Handlers::ChannelUnarchive
