# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module DndUpdated
          # Do not Disturb settings changed for the current user.
          # @see https://api.slack.com/events/dnd_updated
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/dnd_updated.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['dnd_updated'] = Slack::RealTime::Store::Handlers::DndUpdated
