# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module EmailDomainChanged
          # The team email domain has changed.
          # @see https://api.slack.com/events/email_domain_changed
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/email_domain_changed.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['email_domain_changed'] = Slack::RealTime::Store::Handlers::EmailDomainChanged
