# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module FileShared
          # A file was shared.
          # @see https://api.slack.com/events/file_shared
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/file_shared.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['file_shared'] = Slack::RealTime::Store::Handlers::FileShared
