# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module FileCommentDeleted
          # A file comment was deleted.
          # @see https://api.slack.com/events/file_comment_deleted
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/file_comment_deleted.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['file_comment_deleted'] = Slack::RealTime::Store::Handlers::FileCommentDeleted
