# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module FilePublic
          # A file was made public.
          # @see https://api.slack.com/events/file_public
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/file_public.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['file_public'] = Slack::RealTime::Store::Handlers::FilePublic
