# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module FileDeleted
          # A file was deleted.
          # @see https://api.slack.com/events/file_deleted
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/file_deleted.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['file_deleted'] = Slack::RealTime::Store::Handlers::FileDeleted
