# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module GroupClose
          # You closed a group channel.
          # @see https://api.slack.com/events/group_close
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/group_close.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['group_close'] = Slack::RealTime::Store::Handlers::GroupClose
