# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module GroupRename
          # A private group was renamed.
          # @see https://api.slack.com/events/group_rename
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/group_rename.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['group_rename'] = Slack::RealTime::Store::Handlers::GroupRename
