# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module GroupUnarchive
          # A private group was unarchived.
          # @see https://api.slack.com/events/group_unarchive
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/group_unarchive.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['group_unarchive'] = Slack::RealTime::Store::Handlers::GroupUnarchive
