# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module ImHistoryChanged
          # Bulk updates were made to a DM channel's history.
          # @see https://api.slack.com/events/im_history_changed
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/im_history_changed.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['im_history_changed'] = Slack::RealTime::Store::Handlers::ImHistoryChanged
