# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module ImMarked
          # A direct message read marker was updated.
          # @see https://api.slack.com/events/im_marked
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/im_marked.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['im_marked'] = Slack::RealTime::Store::Handlers::ImMarked
