# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module PinAdded
          # A pin was added to a channel.
          # @see https://api.slack.com/events/pin_added
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/pin_added.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['pin_added'] = Slack::RealTime::Store::Handlers::PinAdded
