# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module ReconnectUrl
          # Experimental.
          # @see https://api.slack.com/events/reconnect_url
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/reconnect_url.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['reconnect_url'] = Slack::RealTime::Store::Handlers::ReconnectUrl
