# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module StarRemoved
          # A team member removed a star.
          # @see https://api.slack.com/events/star_removed
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/star_removed.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['star_removed'] = Slack::RealTime::Store::Handlers::StarRemoved
