# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module StarAdded
          # A team member has starred an item.
          # @see https://api.slack.com/events/star_added
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/star_added.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['star_added'] = Slack::RealTime::Store::Handlers::StarAdded
