# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module SubteamUpdated
          # An existing user group has been updated or its members changed.
          # @see https://api.slack.com/events/subteam_updated
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/subteam_updated.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['subteam_updated'] = Slack::RealTime::Store::Handlers::SubteamUpdated
