# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module SubteamCreated
          # A user group has been added to the team.
          # @see https://api.slack.com/events/subteam_created
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/subteam_created.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['subteam_created'] = Slack::RealTime::Store::Handlers::SubteamCreated
