# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module SubteamSelfRemoved
          # You have been removed from a user group.
          # @see https://api.slack.com/events/subteam_self_removed
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/subteam_self_removed.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['subteam_self_removed'] = Slack::RealTime::Store::Handlers::SubteamSelfRemoved
