# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module TeamDomainChange
          # The team domain has changed.
          # @see https://api.slack.com/events/team_domain_change
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/team_domain_change.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['team_domain_change'] = Slack::RealTime::Store::Handlers::TeamDomainChange
