# This file was auto-generated by lib/tasks/real_time.rake

module Slack
  module RealTime
    module Store
      module Handlers
        module UserTyping
          # A channel member is typing a message.
          # @see https://api.slack.com/events/user_typing
          # @see https://github.com/dblock/slack-api-ref/blob/master/events/user_typing.json
          def self.call(_client, _data)
          end
        end
      end
    end
  end
end

Slack::RealTime::Client.events['user_typing'] = Slack::RealTime::Store::Handlers::UserTyping
