# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AdminFunctionsPermissions do
  let(:client) { Slack::Web::Client.new }
  context 'admin.functions.permissions_lookup' do
    it 'requires function_ids' do
      expect { client.admin_functions_permissions_lookup }.to raise_error ArgumentError, /Required arguments :function_ids missing/
    end
  end
  context 'admin.functions.permissions_set' do
    it 'requires function_id' do
      expect { client.admin_functions_permissions_set(visibility: %q[]) }.to raise_error ArgumentError, /Required arguments :function_id missing/
    end
    it 'requires visibility' do
      expect { client.admin_functions_permissions_set(function_id: %q[]) }.to raise_error ArgumentError, /Required arguments :visibility missing/
    end
  end
end
