# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AdminAnalyticsMessages do
  let(:client) { Slack::Web::Client.new }
  context 'admin.analytics.messages_activity' do
    it 'requires channel' do
      expect { client.admin_analytics_messages_activity }.to raise_error ArgumentError, /Required arguments :channel missing/
    end
  end
  context 'admin.analytics.messages_metadata' do
    it 'requires channel' do
      expect { client.admin_analytics_messages_metadata }.to raise_error ArgumentError, /Required arguments :channel missing/
    end
  end
end
