# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AdminConversations do
  let(:client) { Slack::Web::Client.new }
  context 'admin.conversations_setTeams' do
    it 'requires channel_id' do
      expect { client.admin_conversations_setTeams }.to raise_error ArgumentError, /Required arguments :channel_id missing/
    end
  end
end
