# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AdminInviterequests do
  let(:client) { Slack::Web::Client.new }
  context 'admin.inviteRequests_approve' do
    it 'requires invite_request_id' do
      expect { client.admin_inviteRequests_approve }.to raise_error ArgumentError, /Required arguments :invite_request_id missing/
    end
  end
  context 'admin.inviteRequests_deny' do
    it 'requires invite_request_id' do
      expect { client.admin_inviteRequests_deny }.to raise_error ArgumentError, /Required arguments :invite_request_id missing/
    end
  end
end
