# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AdminAppsPermissions do
  let(:client) { Slack::Web::Client.new }
  context 'admin.apps.permissions_add' do
    it 'requires app_id' do
      expect { client.admin_apps_permissions_add }.to raise_error ArgumentError, /Required arguments :app_id missing/
    end
  end
  context 'admin.apps.permissions_list' do
    it 'requires app_id' do
      expect { client.admin_apps_permissions_list }.to raise_error ArgumentError, /Required arguments :app_id missing/
    end
  end
  context 'admin.apps.permissions_remove' do
    it 'requires app_id' do
      expect { client.admin_apps_permissions_remove }.to raise_error ArgumentError, /Required arguments :app_id missing/
    end
  end
  context 'admin.apps.permissions_set' do
    it 'requires app_id' do
      expect { client.admin_apps_permissions_set(permission_type: %q[]) }.to raise_error ArgumentError, /Required arguments :app_id missing/
    end
    it 'requires permission_type' do
      expect { client.admin_apps_permissions_set(app_id: %q[A0000000001]) }.to raise_error ArgumentError, /Required arguments :permission_type missing/
    end
  end
end
