# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AdminWorkflowsPermissions do
  let(:client) { Slack::Web::Client.new }
  context 'admin.workflows.permissions_lookup' do
    it 'requires workflow_ids' do
      expect { client.admin_workflows_permissions_lookup }.to raise_error ArgumentError, /Required arguments :workflow_ids missing/
    end
  end
end
