# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AdminAnalytics do
  let(:client) { Slack::Web::Client.new }
  context 'admin.analytics_getFile' do
    it 'requires type' do
      expect { client.admin_analytics_getFile }.to raise_error ArgumentError, /Required arguments :type missing/
    end
  end
end
