# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AdminFunctions do
  let(:client) { Slack::Web::Client.new }
  context 'admin.functions_list' do
    it 'requires app_ids' do
      expect { client.admin_functions_list }.to raise_error ArgumentError, /Required arguments :app_ids missing/
    end
  end
end
