# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AdminWorkflowsTriggersTypesPermissions do
  let(:client) { Slack::Web::Client.new }
  context 'admin.workflows.triggers.types.permissions_lookup' do
    it 'requires trigger_type_ids' do
      expect { client.admin_workflows_triggers_types_permissions_lookup }.to raise_error ArgumentError, /Required arguments :trigger_type_ids missing/
    end
  end
  context 'admin.workflows.triggers.types.permissions_set' do
    it 'requires id' do
      expect { client.admin_workflows_triggers_types_permissions_set }.to raise_error ArgumentError, /Required arguments :id missing/
    end
  end
end
