# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AppsEventAuthorizations do
  let(:client) { Slack::Web::Client.new }
  context 'apps.event.authorizations_list' do
    it 'requires event_context' do
      expect { client.apps_event_authorizations_list }.to raise_error ArgumentError, /Required arguments :event_context missing/
    end
  end
end
