# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::Apps do
  let(:client) { Slack::Web::Client.new }
  context 'apps_uninstall' do
    it 'requires client_id' do
      expect { client.apps_uninstall(client_secret: %q[]) }.to raise_error ArgumentError, /Required arguments :client_id missing/
    end
    it 'requires client_secret' do
      expect { client.apps_uninstall(client_id: %q[]) }.to raise_error ArgumentError, /Required arguments :client_secret missing/
    end
  end
end
