# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::AssistantThreads do
  let(:client) { Slack::Web::Client.new }
  context 'assistant.threads_setStatus' do
    it 'requires channel_id' do
      expect { client.assistant_threads_setStatus(status: %q[], thread_ts: %q[]) }.to raise_error ArgumentError, /Required arguments :channel_id missing/
    end
    it 'requires status' do
      expect { client.assistant_threads_setStatus(channel_id: %q[C1234567890], thread_ts: %q[]) }.to raise_error ArgumentError, /Required arguments :status missing/
    end
    it 'requires thread_ts' do
      expect { client.assistant_threads_setStatus(channel_id: %q[C1234567890], status: %q[]) }.to raise_error ArgumentError, /Required arguments :thread_ts missing/
    end
  end
  context 'assistant.threads_setSuggestedPrompts' do
    it 'requires channel_id' do
      expect { client.assistant_threads_setSuggestedPrompts(prompts: %q[], thread_ts: %q[]) }.to raise_error ArgumentError, /Required arguments :channel_id missing/
    end
    it 'requires prompts' do
      expect { client.assistant_threads_setSuggestedPrompts(channel_id: %q[C1234567890], thread_ts: %q[]) }.to raise_error ArgumentError, /Required arguments :prompts missing/
    end
    it 'requires thread_ts' do
      expect { client.assistant_threads_setSuggestedPrompts(channel_id: %q[C1234567890], prompts: %q[]) }.to raise_error ArgumentError, /Required arguments :thread_ts missing/
    end
  end
  context 'assistant.threads_setTitle' do
    it 'requires channel_id' do
      expect { client.assistant_threads_setTitle(thread_ts: %q[], title: %q[]) }.to raise_error ArgumentError, /Required arguments :channel_id missing/
    end
    it 'requires thread_ts' do
      expect { client.assistant_threads_setTitle(channel_id: %q[C1234567890], title: %q[]) }.to raise_error ArgumentError, /Required arguments :thread_ts missing/
    end
    it 'requires title' do
      expect { client.assistant_threads_setTitle(channel_id: %q[C1234567890], thread_ts: %q[]) }.to raise_error ArgumentError, /Required arguments :title missing/
    end
  end
end
