# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::Blocks do
  let(:client) { Slack::Web::Client.new }
  context 'blocks_validate' do
    it 'encodes blocks, message, view as json' do
      expect(client).to receive(:post).with('blocks.validate', {blocks: %q[{"data":["data"]}], message: %q[{"data":["data"]}], view: %q[{"data":["data"]}]})
      client.blocks_validate(blocks: {data: ["data"]}, message: {data: ["data"]}, view: {data: ["data"]})
    end
  end
end
