# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::ConversationsRequestsharedinvite do
  let(:client) { Slack::Web::Client.new }
  context 'conversations.requestSharedInvite_approve' do
    it 'requires invite_id' do
      expect { client.conversations_requestSharedInvite_approve }.to raise_error ArgumentError, /Required arguments :invite_id missing/
    end
  end
  context 'conversations.requestSharedInvite_deny' do
    it 'requires invite_id' do
      expect { client.conversations_requestSharedInvite_deny }.to raise_error ArgumentError, /Required arguments :invite_id missing/
    end
  end
end
