# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::ConversationsCanvases do
  let(:client) { Slack::Web::Client.new }
  context 'conversations.canvases_create' do
    it 'requires channel_id' do
      expect { client.conversations_canvases_create }.to raise_error ArgumentError, /Required arguments :channel_id missing/
    end
  end
end
