# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::ConversationsExternalinvitepermissions do
  let(:client) { Slack::Web::Client.new }
  context 'conversations.externalInvitePermissions_set' do
    it 'requires channel' do
      expect { client.conversations_externalInvitePermissions_set(target_team: %q[T726G27TT], action: %q[upgrade]) }.to raise_error ArgumentError, /Required arguments :channel missing/
    end
    it 'requires target_team' do
      expect { client.conversations_externalInvitePermissions_set(channel: %q[C123456], action: %q[upgrade]) }.to raise_error ArgumentError, /Required arguments :target_team missing/
    end
    it 'requires action' do
      expect { client.conversations_externalInvitePermissions_set(channel: %q[C123456], target_team: %q[T726G27TT]) }.to raise_error ArgumentError, /Required arguments :action missing/
    end
  end
end
