# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::Entity do
  let(:client) { Slack::Web::Client.new }
  context 'entity_acknowledgeCommentAction' do
    it 'requires trigger_id' do
      expect { client.entity_acknowledgeCommentAction }.to raise_error ArgumentError, /Required arguments :trigger_id missing/
    end
  end
  context 'entity_presentComments' do
    it 'requires comments' do
      expect { client.entity_presentComments(trigger_id: %q[]) }.to raise_error ArgumentError, /Required arguments :comments missing/
    end
    it 'requires trigger_id' do
      expect { client.entity_presentComments(comments: %q[]) }.to raise_error ArgumentError, /Required arguments :trigger_id missing/
    end
  end
  context 'entity_presentDetails' do
    it 'requires trigger_id' do
      expect { client.entity_presentDetails }.to raise_error ArgumentError, /Required arguments :trigger_id missing/
    end
    it 'encodes metadata as json' do
      expect(client).to receive(:post).with('entity.presentDetails', {trigger_id: %q[], metadata: %q[{"data":["data"]}]})
      client.entity_presentDetails(trigger_id: %q[], metadata: {data: ["data"]})
    end
  end
end
