# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::FunctionsWorkflowsSteps do
  let(:client) { Slack::Web::Client.new }
  context 'functions.workflows.steps_list' do
    it 'requires function_id' do
      expect { client.functions_workflows_steps_list }.to raise_error ArgumentError, /Required arguments :function_id missing/
    end
  end
end
