# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::Reactions do
  let(:client) { Slack::Web::Client.new }
  context 'reactions_add' do
    it 'requires name' do
      expect { client.reactions_add }.to raise_error ArgumentError, /Required arguments :name missing/
    end
  end
  context 'reactions_remove' do
    it 'requires name' do
      expect { client.reactions_remove }.to raise_error ArgumentError, /Required arguments :name missing/
    end
  end
end
