# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::SlackListsDownload do
  let(:client) { Slack::Web::Client.new }
  context 'slackLists.download_get' do
    it 'requires list_id' do
      expect { client.slackLists_download_get(job_id: %q[Le48SKT566]) }.to raise_error ArgumentError, /Required arguments :list_id missing/
    end
    it 'requires job_id' do
      expect { client.slackLists_download_get(list_id: %q[F1234567]) }.to raise_error ArgumentError, /Required arguments :job_id missing/
    end
  end
  context 'slackLists.download_start' do
    it 'requires list_id' do
      expect { client.slackLists_download_start }.to raise_error ArgumentError, /Required arguments :list_id missing/
    end
  end
end
