# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::SlackLists do
  let(:client) { Slack::Web::Client.new }
  context 'slackLists_create' do
    it 'requires name' do
      expect { client.slackLists_create }.to raise_error ArgumentError, /Required arguments :name missing/
    end
  end
  context 'slackLists_update' do
    it 'requires id' do
      expect { client.slackLists_update }.to raise_error ArgumentError, /Required arguments :id missing/
    end
  end
end
