# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::SlackListsItems do
  let(:client) { Slack::Web::Client.new }
  context 'slackLists.items_delete' do
    it 'requires id' do
      expect { client.slackLists_items_delete(list_id: %q[F12345678]) }.to raise_error ArgumentError, /Required arguments :id missing/
    end
    it 'requires list_id' do
      expect { client.slackLists_items_delete(id: %q[Rec1234567]) }.to raise_error ArgumentError, /Required arguments :list_id missing/
    end
  end
  context 'slackLists.items_deleteMultiple' do
    it 'requires ids' do
      expect { client.slackLists_items_deleteMultiple(list_id: %q[F12345678]) }.to raise_error ArgumentError, /Required arguments :ids missing/
    end
    it 'requires list_id' do
      expect { client.slackLists_items_deleteMultiple(ids: %q[]) }.to raise_error ArgumentError, /Required arguments :list_id missing/
    end
  end
  context 'slackLists.items_list' do
    it 'requires list_id' do
      expect { client.slackLists_items_list }.to raise_error ArgumentError, /Required arguments :list_id missing/
    end
  end
end
