# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::TeamExternalteams do
  let(:client) { Slack::Web::Client.new }
  context 'team.externalTeams_disconnect' do
    it 'requires target_team' do
      expect { client.team_externalTeams_disconnect }.to raise_error ArgumentError, /Required arguments :target_team missing/
    end
  end
end
