# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::UsersDiscoverablecontacts do
  let(:client) { Slack::Web::Client.new }
  context 'users.discoverableContacts_lookup' do
    it 'requires email' do
      expect { client.users_discoverableContacts_lookup }.to raise_error ArgumentError, /Required arguments :email missing/
    end
  end
end
