# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::Users do
  let(:client) { Slack::Web::Client.new }
  context 'users_info' do
    it 'requires user' do
      expect { client.users_info }.to raise_error ArgumentError, /Required arguments :user missing/
    end
  end
  context 'users_lookupByEmail' do
    it 'requires email' do
      expect { client.users_lookupByEmail }.to raise_error ArgumentError, /Required arguments :email missing/
    end
  end
  context 'users_setPresence' do
    it 'requires presence' do
      expect { client.users_setPresence }.to raise_error ArgumentError, /Required arguments :presence missing/
    end
  end
end
