# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Slack::Web::Api::Endpoints::WorkflowsTriggersPermissions do
  let(:client) { Slack::Web::Client.new }
  context 'workflows.triggers.permissions_add' do
    it 'requires trigger_id' do
      expect { client.workflows_triggers_permissions_add }.to raise_error ArgumentError, /Required arguments :trigger_id missing/
    end
  end
  context 'workflows.triggers.permissions_list' do
    it 'requires trigger_id' do
      expect { client.workflows_triggers_permissions_list }.to raise_error ArgumentError, /Required arguments :trigger_id missing/
    end
  end
  context 'workflows.triggers.permissions_remove' do
    it 'requires trigger_id' do
      expect { client.workflows_triggers_permissions_remove }.to raise_error ArgumentError, /Required arguments :trigger_id missing/
    end
  end
  context 'workflows.triggers.permissions_set' do
    it 'requires trigger_id' do
      expect { client.workflows_triggers_permissions_set(permission_type: %q[]) }.to raise_error ArgumentError, /Required arguments :trigger_id missing/
    end
    it 'requires permission_type' do
      expect { client.workflows_triggers_permissions_set(trigger_id: %q[Ft0000000001]) }.to raise_error ArgumentError, /Required arguments :permission_type missing/
    end
  end
end
