# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module AdminUsersSession
          #
          # Invalidate a single session for a user by session_id
          #
          # @option options [Object] :session_id
          #   .
          # @option options [Object] :team_id
          #   ID of the team that the session belongs to.
          # @see https://api.slack.com/methods/admin.users.session.invalidate
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.users.session/admin.users.session.invalidate.json
          def admin_users_session_invalidate(options = {})
            throw ArgumentError.new('Required arguments :session_id missing') if options[:session_id].nil?
            throw ArgumentError.new('Required arguments :team_id missing') if options[:team_id].nil?
            post('admin.users.session.invalidate', options)
          end

          #
          # Wipes all valid sessions on all devices for a given user
          #
          # @option options [Object] :user_id
          #   The ID of the user to wipe sessions for.
          # @option options [Object] :mobile_only
          #   Only expire mobile sessions (default: false).
          # @option options [Object] :web_only
          #   Only expire web sessions (default: false).
          # @see https://api.slack.com/methods/admin.users.session.reset
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.users.session/admin.users.session.reset.json
          def admin_users_session_reset(options = {})
            throw ArgumentError.new('Required arguments :user_id missing') if options[:user_id].nil?
            post('admin.users.session.reset', options)
          end
        end
      end
    end
  end
end
