# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module AdminApps
          #
          # Approve an app for installation on a workspace.
          #
          # @option options [Object] :app_id
          #   The id of the app to approve.
          # @option options [Object] :request_id
          #   The id of the request to approve.
          # @option options [Object] :team_id
          #   .
          # @see https://api.slack.com/methods/admin.apps.approve
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.apps/admin.apps.approve.json
          def admin_apps_approve(options = {})
            post('admin.apps.approve', options)
          end

          #
          # Restrict an app for installation on a workspace.
          #
          # @option options [Object] :app_id
          #   The id of the app to restrict.
          # @option options [Object] :request_id
          #   The id of the request to restrict.
          # @option options [Object] :team_id
          #   .
          # @see https://api.slack.com/methods/admin.apps.restrict
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.apps/admin.apps.restrict.json
          def admin_apps_restrict(options = {})
            post('admin.apps.restrict', options)
          end
        end
      end
    end
  end
end
