# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module AdminAppsPermissions
          #
          # Grant permission for entities to access an app that has its permission type set to named_entities
          #
          # @option options [string] :app_id
          #   Encoded ID of the app.
          # @option options [array] :user_ids
          #   List of user IDs to allow for named_entities visibility.
          # @option options [array] :usergroup_ids
          #   List of encoded usergroup IDs.
          # @see https://api.slack.com/methods/admin.apps.permissions.add
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.apps.permissions/admin.apps.permissions.add.json
          def admin_apps_permissions_add(options = {})
            raise ArgumentError, 'Required arguments :app_id missing' if options[:app_id].nil?
            post('admin.apps.permissions.add', options)
          end

          #
          # Returns the permission type of an app and if applicable, includes the entities that have been granted access
          #
          # @option options [string] :app_id
          #   Encoded ID of the app.
          # @see https://api.slack.com/methods/admin.apps.permissions.list
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.apps.permissions/admin.apps.permissions.list.json
          def admin_apps_permissions_list(options = {})
            raise ArgumentError, 'Required arguments :app_id missing' if options[:app_id].nil?
            post('admin.apps.permissions.list', options)
          end

          #
          # Revoke an entity's access to an app that has its permission type set to named_entities
          #
          # @option options [string] :app_id
          #   Encoded ID of the app.
          # @option options [array] :user_ids
          #   List of user IDs whose named_entities access will be revoked.
          # @option options [array] :usergroup_ids
          #   List of encoded usergroup IDs.
          # @see https://api.slack.com/methods/admin.apps.permissions.remove
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.apps.permissions/admin.apps.permissions.remove.json
          def admin_apps_permissions_remove(options = {})
            raise ArgumentError, 'Required arguments :app_id missing' if options[:app_id].nil?
            post('admin.apps.permissions.remove', options)
          end

          #
          # Set the permission type for who can access an app
          #
          # @option options [string] :app_id
          #   Encoded ID of the app.
          # @option options [enum] :permission_type
          #   The type of permission that defines who can access the app.
          # @option options [array] :user_ids
          #   List of user IDs to allow for named_entities visibility.
          # @option options [array] :usergroup_ids
          #   List of encoded usergroup IDs.
          # @see https://api.slack.com/methods/admin.apps.permissions.set
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.apps.permissions/admin.apps.permissions.set.json
          def admin_apps_permissions_set(options = {})
            raise ArgumentError, 'Required arguments :app_id missing' if options[:app_id].nil?
            raise ArgumentError, 'Required arguments :permission_type missing' if options[:permission_type].nil?
            post('admin.apps.permissions.set', options)
          end
        end
      end
    end
  end
end
