# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module AdminAnalyticsMessages
          #
          # Retrieves activity metrics for messages from a given channel.
          #
          # @option options [channel] :channel
          #   Channel ID for channel of the message activity to query.
          # @option options [string] :oldest_ts
          #   Oldest timestamp to include in the results. Defaults to 7 days before current time. If not passed while still passing the latest_ts parameter, defaults to 7 days before latest_ts.
          # @option options [string] :latest_ts
          #   Most recent timestamp to include in results. Defaults to current time. If not passed while still passing the oldest_ts parameter, defaults to 7 days after oldest_ts.
          # @option options [string] :cursor
          #   Paginate through collections of data by setting the cursor parameter to a next_cursor attribute returned by a previous request's response_metadata. Default value fetches the first "page" of the collection.
          # @option options [integer] :limit
          #   Maximum number of entries to return. The maximum limit is 100.
          # @see https://api.slack.com/methods/admin.analytics.messages.activity
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.analytics.messages/admin.analytics.messages.activity.json
          def admin_analytics_messages_activity(options = {})
            raise ArgumentError, 'Required arguments :channel missing' if options[:channel].nil?
            options = options.merge(channel: conversations_id(options)['channel']['id']) if options[:channel]
            if block_given?
              Pagination::Cursor.new(self, :admin_analytics_messages_activity, options).each do |page|
                yield page
              end
            else
              post('admin.analytics.messages.activity', options)
            end
          end

          #
          # Retrieves metadata for a list of messages from a given channel.
          #
          # @option options [channel] :channel
          #   Channel ID for channel containing the messages to query.
          # @option options [string] :oldest_ts
          #   Oldest timestamp to include in the results.
          # @option options [string] :latest_ts
          #   Most recent timestamp to include in the results. If not passed, defaults to current time.
          # @option options [string] :cursor
          #   Paginate through collections of data by setting the cursor parameter to a next_cursor attribute returned by a previous request's response_metadata. Default value fetches the first "page" of the collection. See pagination for more details.
          # @see https://api.slack.com/methods/admin.analytics.messages.metadata
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.analytics.messages/admin.analytics.messages.metadata.json
          def admin_analytics_messages_metadata(options = {})
            raise ArgumentError, 'Required arguments :channel missing' if options[:channel].nil?
            options = options.merge(channel: conversations_id(options)['channel']['id']) if options[:channel]
            if block_given?
              Pagination::Cursor.new(self, :admin_analytics_messages_metadata, options).each do |page|
                yield page
              end
            else
              post('admin.analytics.messages.metadata', options)
            end
          end
        end
      end
    end
  end
end
