# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module AdminAppsMcpServersPermissions
          #
          # List MCP servers for an app with their access control permissions
          #
          # @option options [string] :app_id
          #   Encoded ID of the app.
          # @see https://api.slack.com/methods/admin.apps.mcp.servers.permissions.list
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.apps.mcp.servers.permissions/admin.apps.mcp.servers.permissions.list.json
          def admin_apps_mcp_servers_permissions_list(options = {})
            raise ArgumentError, 'Required arguments :app_id missing' if options[:app_id].nil?
            post('admin.apps.mcp.servers.permissions.list', options)
          end

          #
          # Set the access control permission for who can use an MCP server
          #
          # @option options [string] :app_id
          #   Encoded ID of the app.
          # @option options [string] :server_id
          #   Encoded ID of the MCP server.
          # @option options [enum] :permission_type
          #   The type of permission that defines who can use this MCP server.
          # @option options [array] :user_ids
          #   List of user IDs to set for named_entities or named_entities_exclude.
          # @option options [array] :usergroup_ids
          #   List of encoded usergroup IDs.
          # @see https://api.slack.com/methods/admin.apps.mcp.servers.permissions.set
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/admin.apps.mcp.servers.permissions/admin.apps.mcp.servers.permissions.set.json
          def admin_apps_mcp_servers_permissions_set(options = {})
            raise ArgumentError, 'Required arguments :app_id missing' if options[:app_id].nil?
            raise ArgumentError, 'Required arguments :server_id missing' if options[:server_id].nil?
            raise ArgumentError, 'Required arguments :permission_type missing' if options[:permission_type].nil?
            post('admin.apps.mcp.servers.permissions.set', options)
          end
        end
      end
    end
  end
end
