# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module AppsPermissionsScopes
          #
          # Returns list of scopes this app has on a team.
          #
          # @see https://api.slack.com/methods/apps.permissions.scopes.list
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/apps.permissions.scopes/apps.permissions.scopes.list.json
          def apps_permissions_scopes_list(options = {})
            post('apps.permissions.scopes.list', options)
          end
        end
      end
    end
  end
end
