# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module AppsPermissionsScopes
          #
          # This feature was exclusive to our workspace apps developer preview. The preview has now ended, but fan-favorite features such as token rotation and the Conversations API will become available to classic Slack apps over the coming months.
          #
          # @see https://api.slack.com/methods/apps.permissions.scopes.list
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/apps.permissions.scopes/apps.permissions.scopes.list.json
          def apps_permissions_scopes_list(options = {})
            post('apps.permissions.scopes.list', options)
          end
        end
      end
    end
  end
end
