# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module AppsUserConnection
          #
          # Updates the connection status between a user and an app.
          #
          # @option options [string] :user_id
          #   The ID of the user for the status update.
          # @option options [enum] :status
          #   The status that should be set for the user.
          # @see https://api.slack.com/methods/apps.user.connection.update
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/apps.user.connection/apps.user.connection.update.json
          def apps_user_connection_update(options = {})
            raise ArgumentError, 'Required arguments :user_id missing' if options[:user_id].nil?
            raise ArgumentError, 'Required arguments :status missing' if options[:status].nil?
            post('apps.user.connection.update', options)
          end
        end
      end
    end
  end
end
