# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module Emoji
          #
          # Lists custom emoji for a team.
          #
          # @see https://api.slack.com/methods/emoji.list
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/emoji/emoji.list.json
          def emoji_list(options = {})
            post('emoji.list', options)
          end
        end
      end
    end
  end
end
