# This file was auto-generated by lib/slack/web/api/tasks/generate.rake

module Slack
  module Web
    module Api
      module Endpoints
        module Emoji
          #
          # Lists custom emoji for a team.
          #
          # @see https://api.slack.com/methods/emoji.list
          # @see https://github.com/slackhq/slack-api-docs/blob/master/methods/emoji.list.md
          # @see https://github.com/slackhq/slack-api-docs/blob/master/methods/emoji.list.json
          def emoji_list(options = {})
            post('emoji.list', options)
          end
        end
      end
    end
  end
end
