# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module Entity
          #
          # Provide custom flexpane behavior for Work Objects. Apps call this endpoint to send per-user flexpane metadata to the client.
          #
          # @option options [object] :metadata
          #   URL-encoded JSON object containing flexpane metadata from the app that will be conformed to a Work Object metadata schema, keyed by entity ID.
          # @option options [string] :trigger_id
          #   A reference to the original user action that initiated the request.
          # @option options [boolean] :user_auth_required
          #   Set to true (or 1) to indicate that the user must authenticate to view full flexpane data.
          # @option options [string] :user_auth_url
          #   A custom URL to which users are directed for authentication if required.
          # @option options [Object] :error
          # @see https://api.slack.com/methods/entity.presentDetails
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/entity/entity.presentDetails.json
          def entity_presentDetails(options = {})
            raise ArgumentError, 'Required arguments :trigger_id missing' if options[:trigger_id].nil?
            options = encode_options_as_json(options, %i[metadata])
            post('entity.presentDetails', options)
          end
        end
      end
    end
  end
end
