# This file was auto-generated by lib/slack/web/api/tasks/generate.rake

module Slack
  module Web
    module Api
      module Endpoints
        module Files
          #
          # Gets information about a team file.
          #
          # @option options [file] :file
          #   File to fetch info for
          # @see https://api.slack.com/methods/files.info
          # @see https://github.com/dblock/slack-api-ref/blob/master/methods/files.info.json
          def files_info(options = {})
            throw ArgumentError.new('Required arguments :file missing') if options[:file].nil?
            post('files.info', options)
          end

          #
          # Lists & filters team files.
          #
          # @option options [user] :user
          #   Filter files created by a single user.
          # @option options [Object] :ts_from
          #   Filter files created after this timestamp (inclusive).
          # @option options [Object] :ts_to
          #   Filter files created before this timestamp (inclusive).
          # @option options [Object] :types
          #   Filter files by type:
          #
          #   * `all` - All files
          #   * `posts` - Posts
          #   * `snippets` - Snippets
          #   * `images` - Image files
          #   * `gdocs` - Google docs
          #   * `zips` - Zip files
          #   * `pdfs` - PDF files
          #
          #   You can pass multiple values in the types argument, like `types=posts,snippets`.The default value is `all`, which does not filter the list.
          # @see https://api.slack.com/methods/files.list
          # @see https://github.com/dblock/slack-api-ref/blob/master/methods/files.list.json
          def files_list(options = {})
            post('files.list', options)
          end

          #
          # Uploads or creates a file.
          #
          # @option options [Object] :file
          #   File contents via `multipart/form-data`.
          # @option options [Object] :content
          #   File contents via a POST var.
          # @option options [Object] :filetype
          #   Slack-internal file type identifier.
          # @option options [Object] :filename
          #   Filename of file.
          # @option options [Object] :title
          #   Title of file.
          # @option options [Object] :initial_comment
          #   Initial comment to add to file.
          # @option options [channel] :channels
          #   Comma separated list of channels to share the file into.
          # @see https://api.slack.com/methods/files.upload
          # @see https://github.com/dblock/slack-api-ref/blob/master/methods/files.upload.json
          def files_upload(options = {})
            post('files.upload', options)
          end
        end
      end
    end
  end
end
