# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module OauthV2User
          #
          # Exchanges a temporary OAuth verifier code for a user access token.
          #
          # @option options [string] :client_id
          #   Issued when you created your application. If possible, avoid sending client_id and client_secret as parameters in your request and instead supply the Client ID and Client Secret using the HTTP Basic authentication scheme.
          # @option options [string] :client_secret
          #   Issued when you created your application. If possible, avoid sending client_id and client_secret as parameters in your request and instead supply the Client ID and Client Secret using the HTTP Basic authentication scheme.
          # @option options [string] :code
          #   The code param returned via the OAuth callback.
          # @option options [string] :code_verifier
          #   The code_verifier param used to generate the code_challenge originally. Used for PKCE.
          # @option options [string] :redirect_uri
          #   This must match the originally submitted URI (if one was sent).
          # @option options [string] :grant_type
          #   The grant_type param as described in the OAuth spec.
          # @option options [string] :refresh_token
          #   The refresh_token param as described in the OAuth spec.
          # @see https://api.slack.com/methods/oauth.v2.user.access
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/oauth.v2.user/oauth.v2.user.access.json
          def oauth_v2_user_access(options = {})
            post('oauth.v2.user.access', options)
          end
        end
      end
    end
  end
end
