# This file was auto-generated by lib/slack/web/api/tasks/generate.rake

module Slack
  module Web
    module Api
      module Endpoints
        module Presence
          #
          # Manually set user presence.
          #
          # @option options [Object] :presence
          #   Either `active` or `away`.
          # @see https://api.slack.com/methods/presence.set
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/presence.set.json
          def presence_set(options = {})
            throw ArgumentError.new('Required arguments :presence missing') if options[:presence].nil?
            post('presence.set', options)
          end
        end
      end
    end
  end
end
