# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module Reactions
          #
          # This method adds a reaction (emoji) to a message.
          # Now that file threads work the way you'd expect, the file and file_comment arguments are deprecated. Specify channel and timestamp instead.
          #
          # @option options [Object] :name
          #   Reaction (emoji) name.
          # @option options [channel] :channel
          #   Channel where the message to add reaction to was posted.
          # @option options [file] :file
          #   File to add reaction to. Now that file threads work the way you'd expect, this argument is deprecated. Specify the timestamp and channel of the message associated with a file instead.
          # @option options [Object] :file_comment
          #   File comment to add reaction to. Now that file threads work the way you'd expect, this argument is deprecated. Specify the timestamp and channel of the message associated with a file instead.
          # @option options [Object] :timestamp
          #   Timestamp of the message to add reaction to.
          # @see https://api.slack.com/methods/reactions.add
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/reactions/reactions.add.json
          def reactions_add(options = {})
            throw ArgumentError.new('Required arguments :name missing') if options[:name].nil?
            options = options.merge(channel: channels_id(options)['channel']['id']) if options[:channel]
            post('reactions.add', options)
          end

          #
          # This method returns a list of all reactions for a single item (file, file comment, channel message, group message, or direct message).
          #
          # @option options [channel] :channel
          #   Channel where the message to get reactions for was posted.
          # @option options [file] :file
          #   File to get reactions for.
          # @option options [Object] :file_comment
          #   File comment to get reactions for.
          # @option options [Object] :full
          #   If true always return the complete reaction list.
          # @option options [Object] :timestamp
          #   Timestamp of the message to get reactions for.
          # @see https://api.slack.com/methods/reactions.get
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/reactions/reactions.get.json
          def reactions_get(options = {})
            options = options.merge(channel: channels_id(options)['channel']['id']) if options[:channel]
            post('reactions.get', options)
          end

          #
          # This method returns a list of all items (file, file comment, channel message, group message, or direct message) reacted to by a user.
          #
          # @option options [Object] :cursor
          #   Parameter for pagination. Set cursor equal to the next_cursor attribute returned by the previous request's response_metadata. This parameter is optional, but pagination is mandatory: the default value simply fetches the first "page" of the collection. See pagination for more details.
          # @option options [Object] :full
          #   If true always return the complete reaction list.
          # @option options [Object] :limit
          #   The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the list hasn't been reached.
          # @option options [user] :user
          #   Show reactions made by this user. Defaults to the authed user.
          # @see https://api.slack.com/methods/reactions.list
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/reactions/reactions.list.json
          def reactions_list(options = {})
            options = options.merge(user: users_id(options)['user']['id']) if options[:user]
            if block_given?
              Pagination::Cursor.new(self, :reactions_list, options).each do |page|
                yield page
              end
            else
              post('reactions.list', options)
            end
          end

          #
          # This method removes a reaction (emoji) from an item (file, file comment, channel message, group message, or direct message).
          # One of file, file_comment, or the combination of channel and timestamp must be specified.
          #
          # @option options [Object] :name
          #   Reaction (emoji) name.
          # @option options [channel] :channel
          #   Channel where the message to remove reaction from was posted.
          # @option options [file] :file
          #   File to remove reaction from.
          # @option options [Object] :file_comment
          #   File comment to remove reaction from.
          # @option options [Object] :timestamp
          #   Timestamp of the message to remove reaction from.
          # @see https://api.slack.com/methods/reactions.remove
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/reactions/reactions.remove.json
          def reactions_remove(options = {})
            throw ArgumentError.new('Required arguments :name missing') if options[:name].nil?
            options = options.merge(channel: channels_id(options)['channel']['id']) if options[:channel]
            post('reactions.remove', options)
          end
        end
      end
    end
  end
end
