# This file was auto-generated by lib/slack/web/api/tasks/generate.rake

module Slack
  module Web
    module Api
      module Endpoints
        module Rtm
          #
          # Starts a Real Time Messaging session.
          #
          # @see https://api.slack.com/methods/rtm.start
          # @see https://github.com/slackhq/slack-api-docs/blob/master/methods/rtm.start.md
          # @see https://github.com/slackhq/slack-api-docs/blob/master/methods/rtm.start.json
          def rtm_start(options = {})
            post('rtm.start', options)
          end
        end
      end
    end
  end
end
