# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module Rtm
          #
          # This method begins a Real Time Messaging API session and reserves your application a specific URL with which to connect via websocket.
          #
          # @see https://api.slack.com/methods/rtm.connect
          # @see https://github.com/dblock/slack-api-ref/blob/master/methods/rtm/rtm.connect.json
          def rtm_connect(options = {})
            post('rtm.connect', options)
          end

          #
          # This method begins a Real Time Messaging API session and reserves your application a specific URL with which to connect via websocket.
          #
          # @option options [Object] :simple_latest
          #   Return timestamp only for latest message object of each channel (improves performance).
          # @option options [Object] :no_unreads
          #   Skip unread counts for each channel (improves performance).
          # @option options [Object] :mpim_aware
          #   Returns MPIMs to the client in the API response.
          # @option options [Object] :no_latest
          #   Exclude latest timestamps for channels, groups, mpims, and ims. Automatically sets no_unreads to 1.
          # @see https://api.slack.com/methods/rtm.start
          # @see https://github.com/dblock/slack-api-ref/blob/master/methods/rtm/rtm.start.json
          def rtm_start(options = {})
            post('rtm.start', options)
          end
        end
      end
    end
  end
end
