# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module SlackListsDownload
          #
          # Retrieve List download URL from an export job to download List contents.
          #
          # @option options [string] :list_id
          #   ID of the List to export.
          # @option options [string] :job_id
          #   The ID of the recently started job to export the List.
          # @see https://api.slack.com/methods/slackLists.download.get
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/slackLists.download/slackLists.download.get.json
          def slackLists_download_get(options = {})
            raise ArgumentError, 'Required arguments :list_id missing' if options[:list_id].nil?
            raise ArgumentError, 'Required arguments :job_id missing' if options[:job_id].nil?
            post('slackLists.download.get', options)
          end

          #
          # Initiate a job to export List contents.
          #
          # @option options [string] :list_id
          #   ID of the List to export.
          # @option options [boolean] :include_archived
          # @see https://api.slack.com/methods/slackLists.download.start
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/slackLists.download/slackLists.download.start.json
          def slackLists_download_start(options = {})
            raise ArgumentError, 'Required arguments :list_id missing' if options[:list_id].nil?
            post('slackLists.download.start', options)
          end
        end
      end
    end
  end
end
