# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module SlackListsAccess
          #
          # Revoke access to a List for specified entities.
          #
          # @option options [Object] :list_id
          #   Encoded ID of the List.
          # @option options [array] :channel_ids
          #   List of channels you wish to update access for. Can only be used if user_ids is not provided.
          # @option options [array] :user_ids
          #   List of users you wish to update access for. Can only be used if channel_ids is not provided.
          # @see https://api.slack.com/methods/slackLists.access.delete
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/slackLists.access/slackLists.access.delete.json
          def slackLists_access_delete(options = {})
            raise ArgumentError, 'Required arguments :list_id missing' if options[:list_id].nil?
            post('slackLists.access.delete', options)
          end

          #
          # Set the access level to a List for specified entities.
          #
          # @option options [Object] :list_id
          #   Encoded ID of the List.
          # @option options [Object] :access_level
          #   Desired level of access.
          # @option options [array] :channel_ids
          #   List of channels you wish to update access for. Can only be used if user_ids is not provided.
          # @option options [array] :user_ids
          #   List of users you wish to update access for. Can only be used if channel_ids is not provided.
          # @see https://api.slack.com/methods/slackLists.access.set
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/slackLists.access/slackLists.access.set.json
          def slackLists_access_set(options = {})
            raise ArgumentError, 'Required arguments :list_id missing' if options[:list_id].nil?
            raise ArgumentError, 'Required arguments :access_level missing' if options[:access_level].nil?
            post('slackLists.access.set', options)
          end
        end
      end
    end
  end
end
