# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module TeamProfile
          #
          # This method is used to get the profile field definitions for this team.
          #
          # @option options [Object] :visibility
          #   Filter by visibility.
          # @see https://api.slack.com/methods/team.profile.get
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/team.profile/team.profile.get.json
          def team_profile_get(options = {})
            post('team.profile.get', options)
          end
        end
      end
    end
  end
end
