# This file was auto-generated by lib/slack/web/api/tasks/generate.rake

module Slack
  module Web
    module Api
      module Endpoints
        module Team
          #
          # This method is used to get the access logs for users on a team.
          #
          # @see https://api.slack.com/methods/team.accessLogs
          # @see https://github.com/dblock/slack-api-ref/blob/master/methods/team.accessLogs.json
          def team_accessLogs(options = {})
            post('team.accessLogs', options)
          end

          #
          # This method provides information about your team.
          #
          # @see https://api.slack.com/methods/team.info
          # @see https://github.com/dblock/slack-api-ref/blob/master/methods/team.info.json
          def team_info(options = {})
            post('team.info', options)
          end
        end
      end
    end
  end
end
