# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Endpoints
        module UsersPrefs
          #
          # Returns the user's preferences
          #
          # @see https://api.slack.com/methods/users.prefs.get
          # @see https://github.com/slack-ruby/slack-api-ref/blob/master/methods/users.prefs/users.prefs.get.json
          def users_prefs_get(options = {})
            post('users.prefs.get', options)
          end
        end
      end
    end
  end
end
