# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

module Slack
  module Web
    module Api
      module Errors
        class InvalidProfile < SlackError; end
      end
    end
  end
end
